name: flow v.02

on:
  push:
    branches:    
      - feature-new-workflow

env:
  TEST_ENV: "/home/htec11090/testDir"
  my_string: "Hello world!"


jobs:
  env_variable_test:
    name: env variable fix
    runs-on: self-hosted
    steps:
      - name: Test1
        id: my_string
        run: |
          cd ${{ env.TEST_ENV }}
          pwd
          cat testfile.txt
#          echo "test=world" >> $GITHUB_OUTPUT
      - name: Test2
        run: |
          pwd
          echo "test before variable"
          echo "My string is ${{ env.my_string }}"
#          echo "My real string is ${{ env.my_string }}"
          echo "test after variable"


      

      
