name: flow v.02

on:
  push:
    branches:    
      - feature-new-workflow

env:
  TEST_ENV: "/home/htec11090/testDir"

jobs:
  env_variable_test:
    name: env variable fix v1
    runs-on: self-hosted
    steps:
      - name: Test1
        id: test_1
        run: |
          cd ${{ env.TEST_ENV }}
          touch testfile.txt
          set MY_STRING=123
          echo %MY_STRING%

      - name: Test2
        run: |
          echo "test2"
          echo %MY_STRING%
          echo "test2222"

      

      
